### ISSUE TITLE
Build is not automated

### ISSUE THREAD

**Issue by h1alexbel** [aws/personalize-kafka-connector#3]
we can make Maven build automated using github actions

**Comment by embano1** [comment]
Let me know if I can help as we have a similar scenario and we could share workflows :)

**Comment by h1alexbel** [comment]
@embano1 can we include github actions in this repository for ci purposes?

**Comment by embano1** [comment]
> @embano1 can we include github actions in this repository for ci purposes?

Sure, why not?

**Comment by h1alexbel** [comment]
@embano1 nice, I will do it and send PR
